services:
  dashboard:
    image: docodash:latest
    build:
      target: docodash
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  nginx:
    image: nginx:alpine
    scale: 3
    ports:
      - "80"